### ISSUE TITLE
manjaro如何使用呢

### ISSUE THREAD

**Issue by Leo-Lionni** [riag/manjaro-linux-for-wsl#2]
我用wslconfig /l 查看： 适用于linux的windos子系统 （manajro-linux 默认）
但是我使用bash 没有办法使用到它。我win+R 输入bash，一闪而过。

我之前用的ubuntu是正常的。

**Comment by riag** [comment]
可能是跟 windows 10 版本有关；之前我也遇到过一闪而过，我是在 windows 10 1709 上安装好这个 linux 子系统，然后 windows 10 升级到 1809 版本，运行这个子系统就一闪而过，我是按照提示信息升级这个 linux 子系统，就可以用了

你先打开 powershell, 然后输入 bash，看看有没有提示信息

**Comment by riag** [comment]
2019-05-26 发布了一个版本，你可以试试用这个；还有 README 里加入了使用说明
