### ISSUE TITLE
Source URL error

### ISSUE THREAD

**Issue by hetangx** [riag/manjaro-linux-for-wsl#3]
> [root@DESKTOP-A8B7AQ5 LxRunOffline-v3.4.0_2]# pacman -S nano
resolving dependencies...
looking for conflicting packages...
Packages (1) nano-4.2-1
Total Download Size:   0.44 MiB
Total Installed Size:  2.39 MiB
:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'nano-4.2-1-x86_64.pkg.tar.xz' from mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

Can I change it to other url?

**Comment by hetangx** [comment]
源的地址错误，我看了看，tuna源里已经没有x86_64这个文件夹了，我可以改成普通的吗？

**Comment by riag** [comment]
我这边试了下，没有任何问题。tuna源有 x86_64 文件夹的

![图片](https://user-images.githubusercontent.com/1414506/62614145-69c25d80-b93d-11e9-8f49-5e7428ba860a.png)

**Comment by riag** [comment]
你可以修改 /etc/pacman.d/mirrorlist 这个文件，文件内容改成使用其他镜像地址

**Comment by hetangx** [comment]
解决了，要先执行

> pacman -Syy
