### ISSUE TITLE
百度云真是 慢得令人发指

### ISSUE THREAD

**Issue by daysciao** [riag/manjaro-linux-for-wsl#4]
等到天荒地老

**Comment by riag** [comment]
额，这个我也没办法，目前我只知道百度云可以免费放比较大的文件

**Comment by jun277** [comment]
> 等到天荒地老

IDM+油猴、PanDown等工具都可以高速下载百度云的文件。

**Comment by xBLACKICEx** [comment]
wsltty-launcher.go:48: not found any distro config 是怎么回事 wsltty 配置文件里没有看到 "WSL_DISTRO_NAME 当前 WSL Linux 的 distro name
  WSL_DISTRO_GUID 当前 WSL Linux 的 distro guid
  WSL_DISTRO_ROOTFS_DIR 当前 WSL Linux 的 distro rootfs 路径"
版本是2019 的 power上安装说已经安装了但是启动wsltty 就出错 还需要哪些配置？

**Comment by xBLACKICEx** [comment]
启动了就闪退是怎么回事啊

**Comment by riag** [comment]
打开 powershell, 输入 bash，看能不能正常启动
